Add the Sign-in logic
shua1090/caltact pull request #21
Opened 2023-10-25 21:53 UTC by OlexG

2023-10-25 21:55 UTC, OlexG commented
Closes #16 and #15

2023-10-27 20:29 UTC, reakunen approved these changes
very good job

2023-10-27 20:36 UTC, shua1090 commented
![image](https://github.com/shua1090/caltact/assets/61219106/2050b2e6-02c6-4798-8363-c8ea57958615)

I like the popout, but the white font on logout is kinda mid ngl:
![image](https://github.com/shua1090/caltact/assets/61219106/fa53ef43-583a-41dc-9416-b378540bea78)

2023-10-27 20:43 UTC, shua1090 requested changes

2023-10-27 20:43 UTC, shua1090 commented on pages/signin.tsx
> +        <div className="w-full flex flex-col items-center justify-center">
![image](https://github.com/shua1090/caltact/assets/61219106/743654e8-05a7-4deb-bc91-625ee612eaf9)
Just fix the font and I'll approve

2023-10-27 22:10 UTC, jeremiahliao approved these changes

2023-10-27 22:17 UTC, shua1090 approved these changes
good stuff!

2023-10-27 22:18 UTC, merged