Issue17
shua1090/caltact pull request #28
Opened 2023-11-01 23:44 UTC by shua1090

Example request (missing authentication)
{
    "userid": "01y5hf7YqGZQfzqlgDXj",
    "email": "hello!",
    "name": "shynn.lawrence@gmail.com",
    "phone": "9495724699",
    "instagram": "shua1008",
    "discord": "shua1008",
    "spotify": "shua1008",
    "snapchat": "N/A"
}

2023-11-02 00:56 UTC, OlexG requested changes

2023-11-02 00:56 UTC, OlexG commented on database/index.ts
> +  async addContacts(id: String, contactID: String){
I assume this should be deleted

2023-11-02 00:56 UTC, OlexG commented on database/index.ts
> +  async addContactToID(id: String, contactID: String){
We probably don't need this either

2023-11-02 01:02 UTC, shua1090 commented on database/index.ts
> +  async addContacts(id: String, contactID: String){
deleted

2023-11-02 01:02 UTC, shua1090 commented on database/index.ts
> +  async addContactToID(id: String, contactID: String){
deleted

2023-11-02 01:07 UTC, shua1090 commented on pages/api/types/contact.ts
> +type contact = {
nah lol we'll use id as same for userid and contactid, but contacts will have an array of contacts for each userid (contacts collection is userid-contacts[])

2023-11-02 03:24 UTC, jeremiahliao requested changes
add rest of the parameters to contact object

2023-11-02 03:24 UTC, jeremiahliao commented on pages/api/addContact.ts
for adding contacts on front end and backend, we need to authenticate user both times correct?

2023-11-03 15:38 UTC, shua1090 commented on pages/api/addContact.ts
yeah I think so; changed parameters now btw!

2023-11-03 15:38 UTC, shua1090 commented on database/index.ts
> +  async getContactByPhone(field: string, value: BigInt){
added

2023-11-03 15:39 UTC, shua1090 commented
Example request:
{
    "userid": "01y5hf7YqGZQfzqlgDXj",
    "college": "Cal Poly SLO",
    "major": "Computer Science",
    "firstName": "Brian",
    "lastName": "Mai",
    "github": "reakunen"
}
Any non-filled field will be nulled automatically (shouldn't be a problem considering frontend would handle that for us)

2023-11-03 18:30 UTC, jeremiahliao approved these changes
looks good!

2023-11-03 20:18 UTC, OlexG approved these changes

2023-11-03 20:18 UTC, OlexG commented
LGMT

2023-11-03 22:21 UTC, merged